_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 75.4102
  - 11.9533
  - 3
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 0
name: ''
source: "http://localhost/worldview/mapbox-studio-mapzen-tiles-custom1.json"
styles: 
  - style.mss
template: ''
