_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -90.7031
  - 44.4338
  - 4
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 0
name: ''
source: "http://vector.mapzen.com/osm/tilejson/mapbox.json"
styles: 
  - style.mss
template: ''
