_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 58.5791
  - 23.5438
  - 5
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 0
name: ''
source: "http://localhost/mapzen-tilejsons/mapbox-studio-mapzen-tiles-custom1.json"
styles: 
  - style.mss
template: ''
