_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -7.0862
  - 27.2693
  - 7
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 0
name: ''
source: "http://localhost/worldview/mapbox-studio-mapzen-tiles-custom1.json"
styles: 
  - style.mss
template: ''
