_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 120.5502
  - 24.3784
  - 9
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 0
name: ''
source: "http://localhost/mapzen-tilejsons/mapbox-studio-mapzen-tiles-custom1.json"
styles: 
  - style.mss
template: ''
